# This workflow builds the PawSense executable on macOS using PyInstaller and uploads it as an artifact.

name: Python application (mac)

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

permissions:
    contents: read

jobs:
    build:
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.10
              uses: actions/setup-python@v3
              with:
                  python-version: "3.10"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pyinstaller
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - name: Build with PyInstaller
              run: |
                  pyinstaller --onefile src/pawsense.py
            - name: Upload a Build Artifact
              uses: actions/upload-artifact@v4.6.2
              with:
                  name: pawsense-executable
                  path: dist/pawsense
                  if-no-files-found: warn
                  retention-days: 30
                  compression-level: 6
                  overwrite: false
                  include-hidden-files: false
